<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ERPMarmoraria</AssemblyName>
    <ApplicationIcon>..\appicon.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Authors>ERP Marmoraria</Authors>
    <Product>ERP Marmoraria</Product>
    <Description>Sistema de Gestao Completo para Marmorarias e Granitos</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
  </ItemGroup>

</Project>
